// Typed access + helpers for workout history.
//
// Two sources are merged on the Lifts page:
//   1. Imported history  — data/lifts.json, generated by scripts/parse-strong-csv.mjs
//   2. Logged workouts   — Firestore  users/{uid}/liftSessions  (created in-app)
//
// All helpers are pure functions over a LiftSession[] so they work on the merge.

import liftsData from "@/data/lifts.json";

export interface LiftSet {
  weight: number;
  reps: number;
}

export interface BestSet {
  weight: number;
  reps: number;
  e1rm: number;
}

export interface LiftExercise {
  name: string;
  workingSets: number;
  isBodyweight: boolean;
  sets?: LiftSet[]; // per-set detail (present for logged + freshly imported data)
  best: BestSet;
}

export interface LiftSession {
  id: string;
  date: string; // YYYY-MM-DD
  dateTime: string; // YYYY-MM-DD HH:mm:ss (sortable, local)
  name: string; // e.g. "Workout C"
  durationMin: number;
  volume: number; // sum of weight*reps over logged sets, lb
  exercises: LiftExercise[];
  prCount: number; // estimated PRs (new all-time best est. 1RM)
  source: "imported" | "logged";
  docId?: string; // Firestore id, for logged sessions (enables delete)
}

/** Raw Firestore doc shape for a logged workout. */
export interface LoggedSessionDoc {
  id: string;
  date: string;
  dateTime: string;
  name: string;
  durationMin: number;
  exercises: { name: string; isBodyweight: boolean; sets: LiftSet[] }[];
  createdAt: string;
}

interface LiftsData {
  generatedAt: string | null;
  unit: string;
  sessionCount: number;
  sessions: LiftSession[];
}

const data = liftsData as unknown as LiftsData;

/** Imported (read-only) sessions from the CSV export. */
export const importedSessions: LiftSession[] = data.sessions.map((s) => ({
  ...s,
  source: "imported" as const,
}));

// --- math ------------------------------------------------------------------
export const e1rm = (w: number, r: number) => (w > 0 ? w * (1 + r / 30) : 0);
const score = (w: number, r: number) => (w > 0 ? e1rm(w, r) : r);
const round = (n: number) => Math.round(n * 10) / 10;

/** Best set out of a list, ranked by est. 1RM (or reps for bodyweight). */
export function bestOf(sets: LiftSet[]): BestSet {
  let best = sets[0] ?? { weight: 0, reps: 0 };
  for (const s of sets) {
    if (score(s.weight, s.reps) > score(best.weight, best.reps)) best = s;
  }
  return { weight: best.weight, reps: best.reps, e1rm: round(e1rm(best.weight, best.reps)) };
}

/** Turn a Firestore logged doc into the unified LiftSession shape. */
export function normalizeLogged(doc: LoggedSessionDoc): LiftSession {
  let volume = 0;
  const exercises: LiftExercise[] = doc.exercises.map((ex) => {
    for (const s of ex.sets) volume += s.weight * s.reps;
    return {
      name: ex.name,
      workingSets: ex.sets.length,
      isBodyweight: ex.sets.every((s) => s.weight === 0),
      sets: ex.sets,
      best: bestOf(ex.sets),
    };
  });
  return {
    id: doc.id,
    docId: doc.id,
    date: doc.date,
    dateTime: doc.dateTime,
    name: doc.name,
    durationMin: doc.durationMin,
    volume: Math.round(volume),
    exercises,
    prCount: 0, // computed in mergeSessions
    source: "logged",
  };
}

/** Annotate every session's prCount over the full chronological timeline. */
function withPRCounts(sessionsAsc: LiftSession[]): LiftSession[] {
  const allTimeBest = new Map<string, number>();
  return sessionsAsc.map((sess) => {
    let prs = 0;
    for (const ex of sess.exercises) {
      const sc = score(ex.best.weight, ex.best.reps);
      const prev = allTimeBest.get(ex.name);
      if (prev === undefined) allTimeBest.set(ex.name, sc);
      else if (sc > prev + 1e-6) {
        allTimeBest.set(ex.name, sc);
        prs++;
      }
    }
    return { ...sess, prCount: prs };
  });
}

/**
 * Merge imported + logged sessions, recompute PRs across the combined
 * timeline, and return newest-first.
 */
export function mergeSessions(logged: LoggedSessionDoc[]): LiftSession[] {
  const all = [...importedSessions, ...logged.map(normalizeLogged)];
  all.sort((a, b) => a.dateTime.localeCompare(b.dateTime)); // ascending for PR pass
  const withPRs = withPRCounts(all);
  return withPRs.sort((a, b) => b.dateTime.localeCompare(a.dateTime)); // newest first
}

// --- date / display helpers ------------------------------------------------
const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];
const WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const MONTH_ABBR = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function localDate(date: string): Date {
  const [y, m, d] = date.split("-").map(Number);
  return new Date(y, m - 1, d);
}

export function formatSessionDate(date: string): string {
  const d = localDate(date);
  return `${WEEKDAYS[d.getDay()]}, ${MONTH_ABBR[d.getMonth()]} ${d.getDate()}`;
}

export function monthLabel(date: string): string {
  const d = localDate(date);
  return `${MONTHS[d.getMonth()]} ${d.getFullYear()}`.toUpperCase();
}

export function formatDuration(min: number): string {
  if (!min) return "—";
  const h = Math.floor(min / 60);
  const m = min % 60;
  return h ? (m ? `${h}h ${m}m` : `${h}h`) : `${m}m`;
}

export function formatBestSet(ex: LiftExercise): string {
  if (ex.isBodyweight || ex.best.weight === 0) return `${ex.best.reps} reps`;
  return `${ex.best.weight} lb × ${ex.best.reps}`;
}

/** "2026-06-13 05:31:51" for the current moment (local, sortable). */
export function nowStamp(date: string): string {
  const t = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${date} ${p(t.getHours())}:${p(t.getMinutes())}:${p(t.getSeconds())}`;
}

export function todayISO(): string {
  const t = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${t.getFullYear()}-${p(t.getMonth() + 1)}-${p(t.getDate())}`;
}

// --- aggregates over a session list ----------------------------------------
export interface ProgressPoint {
  date: string;
  e1rm: number;
  weight: number;
  reps: number;
  topReps: number;
}

export function exerciseProgress(sessions: LiftSession[], name: string): ProgressPoint[] {
  return [...sessions]
    .sort((a, b) => a.dateTime.localeCompare(b.dateTime))
    .flatMap((s) => {
      const ex = s.exercises.find((e) => e.name === name);
      if (!ex) return [];
      return [{
        date: s.date,
        e1rm: ex.best.e1rm,
        weight: ex.best.weight,
        reps: ex.best.reps,
        topReps: ex.best.reps,
      }];
    });
}

export function exerciseNames(sessions: LiftSession[]): string[] {
  const counts = new Map<string, number>();
  for (const s of sessions) {
    for (const e of s.exercises) counts.set(e.name, (counts.get(e.name) ?? 0) + 1);
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1]).map(([n]) => n);
}

/** Most recent session (newest-first input) that contains this exercise. */
export function lastExercise(sessionsDesc: LiftSession[], name: string): { date: string; ex: LiftExercise } | null {
  for (const s of sessionsDesc) {
    const ex = s.exercises.find((e) => e.name === name);
    if (ex) return { date: s.date, ex };
  }
  return null;
}

export interface LiftSummary {
  workouts: number;
  totalVolume: number;
  totalPRs: number;
  thisWeek: number;
}

export function summarize(sessions: LiftSession[]): LiftSummary {
  const now = new Date();
  const weekAgo = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7);
  return {
    workouts: sessions.length,
    totalVolume: sessions.reduce((sum, x) => sum + x.volume, 0),
    totalPRs: sessions.reduce((sum, x) => sum + x.prCount, 0),
    thisWeek: sessions.filter((x) => localDate(x.date) >= weekAgo).length,
  };
}

export function groupByMonth(sessionsDesc: LiftSession[]): { label: string; sessions: LiftSession[] }[] {
  const groups: { label: string; sessions: LiftSession[] }[] = [];
  for (const s of sessionsDesc) {
    const label = monthLabel(s.date);
    const last = groups[groups.length - 1];
    if (last && last.label === label) last.sessions.push(s);
    else groups.push({ label, sessions: [s] });
  }
  return groups;
}
